export const GET_CURRENCIES_LIST_REQUEST = 'GET_CURRENCIES_LIST_REQUEST';
export const GET_CURRENCIES_LIST_SUCCESS = 'GET_CURRENCIES_LIST_SUCCESS';
export const GET_CURRENCIES_LIST_ERROR = 'GET_CURRENCIES_LIST_ERROR';

export const CONVERT_FROM_CURRENCY_REQUEST = 'CONVERT_FROM_CURRENCY_REQUEST';
export const CONVERT_FROM_CURRENCY_SUCCESS = 'CONVERT_FROM_CURRENCY_SUCCESS';
