export const GET_CURRENCIES_LIST_REQUEST = 'GET_CURRENCIES_LIST_REQUEST';
export const GET_CURRENCIES_LIST_SUCCESS = 'GET_CURRENCIES_LIST_SUCCESS';
export const GET_CURRENCIES_LIST_ERROR = 'GET_CURRENCIES_LIST_ERROR';
